site_name: "Qcrew crewmate"

theme:
  name: material
  logo: assets/logo.png

  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

extra:
  homepage: https://quantumcrew.org/

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - utils: utils-reference.md
  - qctrl: qctrl-reference.md
